// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEjFpshtJ9Rce9f6jega-4O9UuqEogzVc',
    appId: '1:228188304944:web:24c5b5c0fcb06668795ff5',
    messagingSenderId: '228188304944',
    projectId: 'flutter-app-83bcf',
    authDomain: 'flutter-app-83bcf.firebaseapp.com',
    storageBucket: 'flutter-app-83bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkRSDUTPOyDnje6rqqR9ZcTYh3KHWwNeY',
    appId: '1:228188304944:android:5618579a8513ec3a795ff5',
    messagingSenderId: '228188304944',
    projectId: 'flutter-app-83bcf',
    storageBucket: 'flutter-app-83bcf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9Uq33SeUo-lCYTM0StiQRHPcDnzcYLc',
    appId: '1:228188304944:ios:effbb1253fcd42f7795ff5',
    messagingSenderId: '228188304944',
    projectId: 'flutter-app-83bcf',
    storageBucket: 'flutter-app-83bcf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg9Uq33SeUo-lCYTM0StiQRHPcDnzcYLc',
    appId: '1:228188304944:ios:effbb1253fcd42f7795ff5',
    messagingSenderId: '228188304944',
    projectId: 'flutter-app-83bcf',
    storageBucket: 'flutter-app-83bcf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEjFpshtJ9Rce9f6jega-4O9UuqEogzVc',
    appId: '1:228188304944:web:ff92041622b82c5a795ff5',
    messagingSenderId: '228188304944',
    projectId: 'flutter-app-83bcf',
    authDomain: 'flutter-app-83bcf.firebaseapp.com',
    storageBucket: 'flutter-app-83bcf.firebasestorage.app',
  );
}
