// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyKfYjiyI863i7uHH2IFKrQ76iXNGM5JY',
    appId: '1:170429283602:web:4d39ee84106dc6b4df47cb',
    messagingSenderId: '170429283602',
    projectId: 'suiii-30e80',
    authDomain: 'suiii-30e80.firebaseapp.com',
    storageBucket: 'suiii-30e80.firebasestorage.app',
    measurementId: 'G-ZS5JD04G1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNW1tVPY7jHHVWmRjrirkZdh0cuIq94o',
    appId: '1:170429283602:android:2aa4343903f8cebcdf47cb',
    messagingSenderId: '170429283602',
    projectId: 'suiii-30e80',
    storageBucket: 'suiii-30e80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxbJlYJGnm-6nSjuabLJuTDXEi9mpOWI',
    appId: '1:170429283602:ios:378fd06d7cab30b0df47cb',
    messagingSenderId: '170429283602',
    projectId: 'suiii-30e80',
    storageBucket: 'suiii-30e80.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxbJlYJGnm-6nSjuabLJuTDXEi9mpOWI',
    appId: '1:170429283602:ios:378fd06d7cab30b0df47cb',
    messagingSenderId: '170429283602',
    projectId: 'suiii-30e80',
    storageBucket: 'suiii-30e80.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyKfYjiyI863i7uHH2IFKrQ76iXNGM5JY',
    appId: '1:170429283602:web:d5b16878ff331434df47cb',
    messagingSenderId: '170429283602',
    projectId: 'suiii-30e80',
    authDomain: 'suiii-30e80.firebaseapp.com',
    storageBucket: 'suiii-30e80.firebasestorage.app',
    measurementId: 'G-RMC5M47FMV',
  );
}
