import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_app/services/auth/auth_service.dart';
import 'package:flutter_app/views/login_view.dart';
import 'package:flutter_app/views/main_view.dart';
import 'package:flutter_app/views/register_view.dart';
import 'package:flutter_app/views/verify_view.dart';
import 'firebase_options.dart'; 
import 'package:flutter_app/constants/routes.dart';// Auto-generated by flutterfire configure





void main() async {
  // 1. Ensure Flutter engine bindings are fully loaded
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Launch your app
  runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
        // Global AppBar configuration
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.blue,
          foregroundColor: Colors.white,
          surfaceTintColor: Colors.transparent, // Keeps color pure in Material 3
        ),
      ), // Added missing closing parenthesis for ThemeData
      home: const HomePage(),
      routes : {
        loginRoute : (context) => const LoginView(),
        registerRoute : (context) => const RegisterView(),
        homeRoute : (context) => const MainView(),
        verifyEmailRoute : (context) => const VerifyEmailView(),
      }
    ),
    );
}


class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: AuthService.firebase().initialize(),
        builder: (context, snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.done:
            final user = AuthService.firebase().currentUser;
            if (user != null) {
              if(user.isEmailVerified){
                return const MainView();
              } else {
                return const VerifyEmailView();
              }
            } else {
              return const LoginView();
            }
          default:
              return const CircularProgressIndicator(); 
          }
        }
      );
  }
}

