import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_app/views/login_view.dart';
import 'firebase_options.dart'; 
import 'package:firebase_auth/firebase_auth.dart';// Auto-generated by flutterfire configure

void main() async {
  // 1. Ensure Flutter engine bindings are fully loaded
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Launch your app
  runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
        // Global AppBar configuration
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.blue,
          foregroundColor: Colors.white,
          surfaceTintColor: Colors.transparent, // Keeps color pure in Material 3
        ),
      ), // Added missing closing parenthesis for ThemeData
      home: const HomePage(),
    ),
    );
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home Page'),
      ),
      body: FutureBuilder(
        future: Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        ),
        builder: (context, snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.done:
            final user = FirebaseAuth.instance.currentUser;
            if (user?.emailVerified ?? false) {
              print('User is signed in and email is verified');
            } else {
              print('User is signed in but email is not verified');
            }
            return const Text('Done👌');
          default:
              return const Text('Loading...');
          }
        }
      ),
    );
  }
}
